name: Build flatpak
run-name: Building ${{ github.ref }} from ${{ github.actor }}
env:
  SIGNAL_FLATPAK: org.signal.Signal_Beta

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [beta]
  push:
    branches: [beta]
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    if: ${{ always() }} 
    steps:
      - name: Setup flatpak build env
        run: sudo apt-get -y upgrade && sudo apt-get -y install wget gnupg2 flatpak flatpak-builder
      - name: Add Flathub repo
        run: wget https://flathub.org/repo/flathub.gpg && sudo flatpak remote-add --if-not-exists --gpg-import=flathub.gpg flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Clone the PR
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.SIGNAL_BETA_UPDATE_TOKEN }}'

      - name: Save app version
        run: SIGNAL_V=$(perl -ne '/(?<=signal\-desktop\-beta\_)([a-zA-Z0-9_\-.]*?)(?=_amd64)/ && print "$1"' < "$SIGNAL_FLATPAK.yaml") && echo "SIGNAL_VERSION=$SIGNAL_V" >> "$GITHUB_ENV"
      - name: Build the image
        run: sudo flatpak-builder --install-deps-from=flathub --repo=repo builddir "$SIGNAL_FLATPAK.yaml"
      - name: Install the image
        run: sudo flatpak install --noninteractive ./repo "$SIGNAL_FLATPAK"

      - name: Generate single-file bundle
        run: sudo flatpak build-bundle ./repo "$SIGNAL_FLATPAK.flatpak" "$SIGNAL_FLATPAK" && sudo chmod 777 "./$SIGNAL_FLATPAK.flatpak"
      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: signal-desktop-beta-v${{ env.SIGNAL_VERSION }}
          path: ./${{ env.SIGNAL_FLATPAK }}.flatpak
          if-no-files-found: error

